[package]
name = "trust_antivirus"
version = "1.0.0"
authors = ["Adam Childs <adamdchilds@gmail.com>"]

[dependencies]
clap = "2.24.2"
md5 = "0.3.4"
rayon = "0.7.1"
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.2"
walkdir = "1.0.7"
